codecov:
  require_ci_to_pass: yes
  token: "4f78312c-8c8c-4738-a84d-69c626daaf2e"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic, target coverage takes base commit, allow to drop by 2%
        target: auto
        threshold: 0.5%
        base: auto 
        paths: 
          - "src"
    patch:
      default:
        # basic, target coverage 30%, allow to drop by 0% to get a success
        target: 30%
        threshold: 0%
        base: auto
        paths: 
          - "src"
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no